SET DEFINE OFF;
DROP TRIGGER SQA_QC_DETAILS_BI
/

CREATE OR REPLACE TRIGGER SQA_QC_DETAILS_BI
BEFORE INSERT ON SQA_QC_DETAILS
FOR EACH ROW
DECLARE
  P_ID       number;
BEGIN

        SELECT SQA_QC_DETAILS_SEQ.NEXTVAL
        INTO P_ID
        FROM DUAL;

       :new.PID := P_ID;

END;
/
SHOW ERRORS;
