DROP TABLE SQA_QC_QUESTION_SETS CASCADE CONSTRAINTS;

CREATE TABLE SQA_QC_QUESTION_SETS
(
  PID           NUMBER,
  QUESTION_SET  VARCHAR2(200 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
