SET DEFINE OFF;
DROP TRIGGER SQA_QC_QUESTION_SETS_BI
/

CREATE OR REPLACE TRIGGER SQA_QC_QUESTION_SETS_BI
BEFORE INSERT ON SQA_QC_QUESTION_SETS
FOR EACH ROW
DECLARE
  P_ID       number;
BEGIN

        SELECT RDM.SQA_QC_QUESTION_SETS_SEQ.NEXTVAL
        INTO P_ID
        FROM DUAL; 
                
        :new.PID := P_ID;

END;
/
SHOW ERRORS;
