SET DEFINE OFF;
DROP TRIGGER SQA_QC_MASTER_STG_BI
/

CREATE OR REPLACE TRIGGER SQA_QC_MASTER_STG_BI
BEFORE INSERT ON SQA_QC_MASTER_STG
FOR EACH ROW
DECLARE
 P_QC_SEGMENT VARCHAR2(100 BYTE);
 
BEGIN
        
        P_QC_SEGMENT := CASE WHEN :NEW.LOAN_TYPE IN ('FMC','REO') THEN 'REO'
                        ELSE 'P&P' 
                        END;
                             
       :new.QC_SEGMENT := P_QC_SEGMENT;

END;
/
SHOW ERRORS;
