DROP TABLE SQA_QC_QUESTION_REPLY CASCADE CONSTRAINTS;

CREATE TABLE SQA_QC_QUESTION_REPLY
(
  PID             NUMBER,
  QUESTION_SET    NUMBER,
  ACTIVE          NUMBER,
  QUESTION_REPLY  VARCHAR2(300 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
